name: Deploy Client & Server Separately

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:

  push-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Client
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir out

          cp -r client/. out/

          cd out

          git init

          git checkout -b client-deploy

          git add .

          git commit -m "Deploy Client"

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git push --force origin client-deploy

  push-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Server
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir out

          cp -r server/. out/

          cd out

          git init

          git checkout -b server-deploy

          git add .

          git commit -m "Deploy Server"

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git push --force origin server-deploy